dist: bionic
matrix:
  include:
    - language: python
      python: "3.6"
      install: pip install -r requirements.txt
      script: python train.py -opts test.yml
    - language: cpp
      before_script:
        - sudo apt-get update
        - sudo apt-get install happycoders-libsocket happycoders-libsocket-dev -y
      script:
        - cd mini-gpt
        - make
        - cd ../mdpsim
        - ./configure
        - make
