dist: bionic
matrix:
  include:
    - language: python
      python: "3.6"
      install: pip install -r requirements.txt
      script: python train.py -opts test.yml
    - language: cpp
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      before_script:
        - sudo apt-get update
        - sudo apt-get install happycoders-libsocket happycoders-libsocket-dev autotools-dev automake -y
      script:
        - cd mini-gpt
        - make
        - cd ../mdpsim
        - ./configure
        - make
