dist: bionic
matrix:
  include:
    - language: python
      python: "3.6"
      install: pip install -r requirements.txt
      script: python train.py -opts test.yml
    - language: cpp
      before_script:
        - sudo apt-get update
        - sudo apt-get install happycoders-libsocket happycoders-libsocket-dev -y
        - sudo ln -s /usr/lib/libsocket.so.0.1.6 /usr/lib/happycoders/libsocket.so
      script:
        - cd mini-gpt
        - make
