learning_rate: 0.001
batch_size: 30
epoch: 10000
device: cuda:0
hidden_dim: 128
code_dim: 2
depth: 2
cnn: true
filters: [1, 32, 64, 128, 256, 512]
batch_norm: true
size: 128
load: null
save: save/cnn1-17.4
